# Generated by Django 2.0.7 on 2020-05-20 08:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='slot1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot10',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 284442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot12',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 284442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot13',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 284442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot14',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 284442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot2',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 282991, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot3',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 283917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot4',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 283917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot5',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 283917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot6',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 283917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot7',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 283917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot8',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 283917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot9',
            field=models.TimeField(default=datetime.datetime(2020, 5, 20, 8, 0, 44, 284442, tzinfo=utc)),
        ),
    ]
