# Generated by Django 2.0.7 on 2020-05-24 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_auto_20200520_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
    ]
