# Generated by Django 2.0.7 on 2020-05-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_auto_20200524_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounsellorAvailability',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='slot1',
            new_name='workhours',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot10',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot12',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot13',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot14',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot2',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot3',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot4',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot5',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot6',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot7',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot8',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slot9',
        ),
    ]
