# Generated by Django 2.0.7 on 2020-05-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0006_auto_20200527_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availability',
            new_name='Shifts',
        ),
    ]
