# Generated by Django 2.0.7 on 2020-05-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0007_auto_20200530_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
