# Generated by Django 2.0.7 on 2020-06-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0001_initial'),
        ('availability', '0008_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='date',
            new_name='availableDate',
        ),
        migrations.AddField(
            model_name='availability',
            name='councellor',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='counsellor.Counsellor'),
        ),
    ]
