# Generated by Django 2.0.7 on 2020-05-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(default='mydjango123', max_length=32)),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(default='no_name@gmail.com', max_length=254)),
                ('education', models.TextField(blank='true', null='true')),
            ],
        ),
    ]
