# Generated by Django 2.0.7 on 2020-06-07 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('counsellor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.CharField(max_length=100)),
                ('client', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('counsellor', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='counsellor.Counsellor')),
            ],
        ),
    ]
